### PR TITLE
Add remaining code

### LINKED ISSUE #2: Add code from other chapters
We want to make sure it's all incorporated here.

Suggested by @lkr-ind but I'm happy to be assigned it!

### LINKED ISSUE #3: Markdownlint hook is broken
See: https://github.com/ImperialCollegeLondon/poetry_template_2/pull/41

### PR DESCRIPTION
**Pull request by alexdewar**
This PR adds the remaining code for the unit testing course and the necessary CMakeLists.txt files for building it.

In general I have tried to avoid modifying the code, as I want to keep it in sync with the lesson content in the other repo, but I have changed a few things:

- I reformatted everything with clang-format for consistency (I changed the style a little from the last PR for tidiness)
- I replaced the old C-style header guards (i.e. `#define MY_HEADER_H`) with the more modern `#pragma once`
- I fixed a few compiler warnings for trivial issues so that the CI would pass
- I did a small amount of misc tidying (fixing up file names for consistency etc.)

As it seems that all the tests for this code *should* pass, I changed the CI config to ensure that they do.

Fixes #2. Fixes #3.

### CODE REVIEW

**Review by dalonsoa — APPROVED** [review]
I've limit the review to make sure I understand  how the code is structured, what cmake is doing and that I know how to run the stuff in Visual Studio on Windows. All looks good and seem to make sense (and all tests pass!).

**Review by jamesturner246 — APPROVED** [review]
Nothing pops out that it's wrong.

One question: in CMake, is there a way to have project root grounded abs paths, or does everything need to be a relative path?

**Comment by alexdewar** [comment]
You mean use paths that are relative to the root of the repo rather than the `CMakeLists.txt` files? I don't think there's a way of doing that, unfortunately.

**Comment by jamesturner246** [comment]
Ah no worries. It's the same for recursive GPU make then. No biggie.

**Review by lkr-ind — APPROVED** [review]
Thanks @alexdewar . Everything looks good.

**Pull request merged**
